name: Build and run unit test

on:
  push:
    branches: [ "develop" ]
jobs:
  build_and_run_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Test
      #run: dotnet test HouseRentingSystem.UnitTests --no-build --verbosity normal # working
      #Uopdate to Long command to test
      run: dotnet test HouseRentingSystem.UnitTests --no-build --verbosity normal

