# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and run Integration Tests using .NET

on:
  push:
    branches: [ "staging" ]

jobs:
  build_run_integration_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run integration tests
      run: dotnet test HouseRentingSystem.Tests\HouseRentingSystem.Tests.csproj --no-build --verbosity normal
