

name: Build and run the Unit tests

on:
  push:
    branches: [ "Dev" ]


jobs:
  build_run_uni_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the App
      run: dotnet build --no-restore
    - name: Run Unit Test
      run: dotnet test HouseRentingSystem.UnitTests/HouseRentingSystem.UnitTests.csproj --no-build --verbosity normal
