name: Build and Run Unit Tests

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # или друга версия според изискванията
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test HouseRentingSystem.UnitTests\HouseRentingSystem.UnitTests.csproj --no-build --verbosity normal
