name: .NET Build and Test

on:
  push:
    branches:
      - develop
      - staging
  pull_request:
    branches:
      - develop
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore HouseRentingSystem.sln

      - name: Build
        run: dotnet build HouseRentingSystem.sln --no-restore

      - name: Run Unit Tests
        if: github.ref == 'refs/heads/develop'
        run: dotnet test HouseRentingSystem.UnitTests/HouseRentingSystem.UnitTests.csproj --no-build --verbosity normal

      - name: Run Integration Tests
        if: github.ref == 'refs/heads/staging'
        run: dotnet test HouseRentingSystem.Tests/HouseRentingSystem.Tests.csproj --no-build --verbosity normal
